### ISSUE TITLE
Game freezes randomly after respawn

### ISSUE THREAD

**Issue by goodboy10** [PowerOfUniverse/Krunker.io-Cheats#10]
https://imgur.com/a/K8wxt8L
i can still hear other people shooting but im frozen
![image](https://user-images.githubusercontent.com/18133966/45128361-c2d7bd80-b1d1-11e8-87a4-4055d02a0107.png)

**Comment by goodboy10** [comment]
https://imgur.com/a/K8wxt8L
i can still hear other people shooting
![image](https://user-images.githubusercontent.com/18133966/45128361-c2d7bd80-b1d1-11e8-87a4-4055d02a0107.png)

**Comment by PowerOfUniverse** [comment]
Before the last update also this error existed?

**Comment by goodboy10** [comment]
no only after last update, It freezes after pressing shift with right click aim turned on

**Comment by goodboy10** [comment]
after turning off auto aim it does not freeze when I press shift or z 🤔

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/commit/44cfdc06dc9d70779040f6e863f8981b4b0553c4
