### ISSUE TITLE
i wont respawn

### ISSUE THREAD

**Issue by saintsxDkuba** [PowerOfUniverse/Krunker.io-Cheats#11]
when i click to play screen is frozen but i hear normal sounds...

**Comment by PowerOfUniverse** [comment]
A new version of the game has come out, I will fix it right away.

**Comment by TheZacharyHunter** [comment]
Wow, you are very fast. Thanks, was about to post this.

**Comment by Mc4azy** [comment]
but you can still play if you only turn player name on. And thx to the dev for that fast responding and fast fixing for the cheat Good job! if my paypal wouldnt be locket atm i would donate LOL

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/commit/600dd216784c0d08269aad05ccb4d1963e36931a

**Comment by PowerOfUniverse** [comment]
fdf36a2

No problem ;)
