### ISSUE TITLE
Freezing by spawning into the game

### ISSUE THREAD

**Issue by BlizzardFox** [PowerOfUniverse/Krunker.io-Cheats#13]
Unsure if this is only me, or affects everyone using the script.
Game freezes right before spawning and never goes away until you refresh the page.
![issue_krunker](https://user-images.githubusercontent.com/43051013/45189094-2c64c580-b1ec-11e8-921c-0838c36093f2.png)

Update: Seems to be caused by any form of gun-related scripting. Anything like NoRecoil and AutoAim cause this problem.

**Comment by PowerOfUniverse** [comment]
Can you send a picture from the chrome://extensions/  ?

**Comment by PowerOfUniverse** [comment]
And from the console (with errors)

**Comment by BlizzardFox** [comment]
Yeah, here they are.
![image](https://user-images.githubusercontent.com/43051013/45246074-2803df80-b2b4-11e8-971d-e696901236b6.png)
![image](https://user-images.githubusercontent.com/43051013/45246085-4964cb80-b2b4-11e8-978a-8bdaf07d191a.png)

**Comment by IAmAHumanIThink** [comment]
same

**Comment by BlizzardFox** [comment]
Issue seems to have been fixed in latest version (0.9.9994), going to close this issue.
