### ISSUE TITLE
Activation

### ISSUE THREAD

**Issue by 1tarko** [PowerOfUniverse/Krunker.io-Cheats#14]
Please, how do i change the enable key from z to x or other, it will be easier to apply the scope, thanks.

**Comment by PowerOfUniverse** [comment]
Ok, I will add the function of an independent change later.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/commit/b54e6e0681ebb2145b6ec34f236f1fcafb97b44d
