### ISSUE TITLE
Sniper Only

### ISSUE THREAD

**Issue by IAmAHumanIThink** [PowerOfUniverse/Krunker.io-Cheats#15]
With this script, only snipers and shotguns work. ARs and smgs don't do any damage

**Comment by PowerOfUniverse** [comment]
In my free time I will try to improve the user's positioning.

**Comment by IAmAHumanIThink** [comment]
Ok

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/projects/1
