### ISSUE TITLE
[Suggestion] Ghost Mode

### ISSUE THREAD

**Issue by BlizzardFox** [PowerOfUniverse/Krunker.io-Cheats#17]
Maybe try to make a "ghost mode" that disables all the cheats and/or hides the cheat config menu.
Might be useful for people playing with friends who want them to screenshare to see if they are cheating or not.
Just a suggestion though

**Comment by PowerOfUniverse** [comment]
Currently, you can turn off the cheat by pressing the z button. This is not enough ;)?

**Comment by BlizzardFox** [comment]
By what I mean, is that there could be a button/bind that, like you said, can hide the button for menu. But for the turning off the cheats part, I simply forgot that there was button for it.
Having a button for hiding the cheat menu could mean that people playing with friends can hide the menu and then pretty much bypass, for example on Discord, a screenshare if his/her friends ask to see their screen to check if they are cheating or not.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/projects/1
