### ISSUE TITLE
Toggles + Hold key for aimbot

### ISSUE THREAD

**Issue by TheZacharyHunter** [PowerOfUniverse/Krunker.io-Cheats#2]
Hey! Love the aimbot on here. Could you add toggles for all of the features and a key where if you hold it, the aimbot would work? This would make detection of the aimbot for people near you in real life and doing 1080's easier! Thanks!

**Comment by PowerOfUniverse** [comment]
Ok, I will add it soon.

**Comment by TheZacharyHunter** [comment]
Thanks for that insanely fast reply. Also thanks for the insanely fast update to the new patch. Thanks again.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/commit/b7dcad269a3d498db5125026a202494c0d1a08b8

**Comment by betterbabywipes** [comment]
the hack doesn't work?
Keeps loading...

**Comment by PowerOfUniverse** [comment]
Have you tried to refresh the page?

**Comment by betterbabywipes** [comment]
yes as well as closing my tab

**Comment by betterbabywipes** [comment]
it works now, thanks :D
your the best dev :)

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/commit/2840732e20468dd1aa90434515affc3aa5712f99

**Comment by TheZacharyHunter** [comment]
Wow thank you so much!
