### ISSUE TITLE
Infinite ammo?

### ISSUE THREAD

**Issue by idrizdi** [PowerOfUniverse/Krunker.io-Cheats#21]
Same as title

**Comment by Heraku69** [comment]
LOL

**Comment by Heraku69** [comment]
not possible m8, but keep believing

**Comment by Heraku69** [comment]
as

**Comment by Heraku69** [comment]
asdasd

**Comment by Heraku69** [comment]
asdasdasd

**Comment by PanKot** [comment]
![image](https://user-images.githubusercontent.com/43040661/45383494-ae4d5800-b60b-11e8-9e55-1795ba9697d5.png)

**Comment by idrizdi** [comment]
![image](https://user-images.githubusercontent.com/30215382/45384598-bf4b9880-b60e-11e8-86ee-1cd6a8acb586.png)

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/projects/1
