### ISSUE TITLE
Krunker has blocked this extension

### ISSUE THREAD

**Issue by TheZacharyHunter** [PowerOfUniverse/Krunker.io-Cheats#5]
If you try to load the game with this extension on, it is permanently connecting. When I turn it off Krunker works again. I am in a clan so if you could possibly fix this within the next day or 2 that would be great, but I know your busy with irl stuff too. Thanks again.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/commit/f6f8e026087f6a26732995fcf653573cb6959e20
