### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by TheZacharyHunter** [PowerOfUniverse/Krunker.io-Cheats#6]
Could you add one of those please? Sorry to put so many issues up today :(

**Comment by PowerOfUniverse** [comment]
But in total, on github you have exactly described changes :).

https://github.com/PowerOfUniverse/Krunker.io-Cheats/commits?author=PowerOfUniverse

**Comment by TheZacharyHunter** [comment]
Yeah but some of us (maybe just me D:) don't understand the game.js code. I understand if you just don't wanna write it out.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/blob/master/changelog.txt

I added ;)

**Comment by betterbabywipes** [comment]
Thanks so much! You da best man :D
