### ISSUE TITLE
Krunker permanently loading when using cheat again :(

### ISSUE THREAD

**Issue by TheZacharyHunter** [PowerOfUniverse/Krunker.io-Cheats#7]
As the title says. Thanks for the fix in advance.

**Comment by PowerOfUniverse** [comment]
Can you send a picture from the console (with errors)?

**Comment by TheZacharyHunter** [comment]
https://imgur.com/a/NdUf05u

**Comment by PowerOfUniverse** [comment]
And from: chrome://extensions/

**Comment by TheZacharyHunter** [comment]
https://imgur.com/a/KnnUB6F this what you want?

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/45039919-01039e80-b065-11e8-8f3e-32767b0ba077.png)
I recommend updating the version :)

**Comment by TheZacharyHunter** [comment]
Oh, like an idiot I used the previous. I downloaded the new version, then deleted it and reinstalled the same version. Thank you!
