### ISSUE TITLE
Request For Feature [ENHANCEMENT]

### ISSUE THREAD

**Issue by goodboy10** [PowerOfUniverse/Krunker.io-Cheats#9]
would it be possible to add an option in the settings to enable the aimbot only when right click is being held?

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Krunker.io-Cheats/commit/c2e471a313af67519a54d28b2beca1dd616be6eb

**Comment by goodboy10** [comment]
Thanks
